/* ========================================================================
 * Copyright 2014 besitosbesitos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 besitosbesitos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_memberModel'], function() {
    App.Model.MemberModel = App.Model._MemberModel.extend({
 	validate: function(attrs,options){
            var validationMessage = "";
            if(!attrs.name){
                validationMessage = "The name can't be empty.";
            }
             if(!attrs.lastName){
                validationMessage = validationMessage + "The last name can't be empty.";
            }
             if(!attrs.firstName){
                validationMessage = validationMessage + "The first name can't be empty.";
            }
             if(!attrs.birthDate){
                validationMessage = validationMessage + "The birthdate can't be empty.";
            }
            if(attrs.birthDate){
                      var x=new Date();
                      var fecha = attrs.birthDate.split("/");
                      x.setFullYear(fecha[2],fecha[1]-1,fecha[0]);
                      var today = new Date();
                      if (x >= today)
                      {validationMessage = validationMessage + "No valid date.";}
                      console.log(x.getFullYear()-today.getFullYear());
                      if((today.getFullYear()-x.getFullYear())>100)
                          {validationMessage = validationMessage + "No valid date2 .";}
                   
                }
     
            
             if(!attrs.docNumber){
                validationMessage = validationMessage + "The document number can't be empty.";
            }
            if(attrs.docNumber.length < 5){
                validationMessage = validationMessage + "no valid Document number.";
            }
             if(!attrs.documenttypeId){
                validationMessage = validationMessage + "The document type id can't be empty.";
            }
             if(!attrs.partnerId){
                validationMessage = validationMessage + "The partner can't be empty.";
            }
            
            if(validationMessage.length>0){
               return validationMessage;
            }
        }
    });
    App.Model.MemberList = App.Model._MemberList.extend({
        model: App.Model.MemberModel
    });
    return  App.Model.MemberModel;
});